---
  - name: Update all packages
    yum:
      name: "*"
      state: latest

  - name: Install Git
    shell: yum install -y git

  - name: Check Git version
    command: git --version
    register: git_version
    become: no
    ignore_errors: true

  - name: Display Git version
    debug:
      msg: "Git version: {{ git_version.stdout }}"